package it.polimi.elet.selflet

#list any import classes here.
import it.polimi.elet.selflet.events.*;
import it.polimi.elet.selflet.events.ability.*;
import it.polimi.elet.selflet.events.behavior.*;
import it.polimi.elet.selflet.events.message.*;
import it.polimi.elet.selflet.events.prediction.*;
import it.polimi.elet.selflet.events.property.*;
import it.polimi.elet.selflet.events.drools.*;
import it.polimi.elet.selflet.events.service.*;
import it.polimi.elet.selflet.events.type.*;
import it.polimi.elet.selflet.exceptions.*;
import it.polimi.elet.selflet.negotiation.*;
import it.polimi.elet.selflet.behavior.IBehavior;
import it.polimi.elet.selflet.knowledge.IServiceKnowledge;
import it.polimi.elet.selflet.negotiation.ServiceOfferModeEnum;
import it.polimi.elet.selflet.negotiation.ServiceAskModeEnum;
import it.polimi.elet.selflet.service.*;
import it.polimi.elet.selflet.service.utilization.*;
import it.polimi.elet.selflet.knowledge.KnowledgeBase;
import it.polimi.elet.selflet.autonomic.IAutonomicActuator;
import it.polimi.elet.selflet.autonomic.predictive.*;
import it.polimi.elet.selflet.autonomic.predictive.models.*;
import it.polimi.elet.selflet.action.*;
import it.polimi.elet.selflet.optimization.*;
import it.polimi.elet.selflet.optimization.generators.*;

import java.util.*;

#declare any global variables here (these are those added to the working memory)
#their scope is limited to the rules only

global INegotiationManager 		negotiationManager;
global IAutonomicActuator 		autonomicActuator;
global IServiceKnowledge 		serviceKnowledge;
global KnowledgeBase 			knowledgeBase;
 

#GENERIC POLICIES


rule "needed Service Policy"
	
	when
		event:	ServiceNeededEvent()
		
	then 
		activateNeededService(event, autonomicActuator);
end

	
function void activateNeededService(ServiceNeededEvent event, IAutonomicActuator autonomicActuator){		
	
	String serviceName = event.getServiceName();
	String destination 	= event.getResultDestination();
	RunningService callingService = event.getCallingService();
		
	#System.out.println("Executing service: " + serviceName);
	
	autonomicActuator.executeService(serviceName, destination, callingService);
}

