package it.polimi.elet.selflet.optimization.generators;


import it.polimi.elet.selflet.optimization.actions.IOptimizationAction;

import java.util.Collection;

/**
 * An interface for action generators. Each generator produce exatcly one kind
 * of optimization actions
 * 
 * @author Nicola Calcavecchia <calcavecchia@gmail.com>
 * */
public interface IActionGenerator {

	/**
	 * Returns a collection of possible optimization actions generated by this
	 * action generator
	 * */
	Collection<? extends IOptimizationAction> generateActions();

}
