package it.polimi.elet.selflet.load;

/**
 * Describes the kind of load generated by the load generator
 * 
 * @author Nicola Calcavecchia <calcavecchia@gmail.com>
 * */
public enum LoadType {

	Constant,

	Poisson,

	LogNormal

}
